### ISSUE TITLE
Add a .env-sample file to project root

### ISSUE THREAD

**Issue by mcruzdev** [mcruzdev/platformoon-apps#3]
We need a .env file as sample, the .env-sample file must be the following variables:

- PLATFORMOON_GH_TOKEN=
- PLATFORMOON_GH_ORG=
- REGISTRY_ACCOUNT=

Each environment variable must have a comment with a simple description.

**Comment by SurajPrakash24** [comment]
Can you please assign this issue. I want to contribute.

**Comment by mcruzdev** [comment]
Hi @SurajPrakash24, TY for helping, go ahead!

**Comment by mcruzdev** [comment]
Closed by #4
